export default {
	API_URL: process.env.REACT_APP_SERVER_URL,
	FESTIVAL_NAME: process.env.REACT_APP_FESTIVAL_NAME,
	FESTIVAL_START_DATE: process.env.REACT_APP_FESTIVAL_START_DATE,
	FESTIVAL_END_DATE: process.env.REACT_APP_FESTIVAL_END_DATE,
}